version: '3.3'
services:
  mq:
    image: ibmcom/mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    ports:
      - "1414:1414"
  webapp1:
    image: tomcat
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - "mq"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '46000:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    depends_on:
      - "mq"
  

volumes:
  my-db: